// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfaM2a85lRB37xtlTsGTO8V93njRXwkk',
    appId: '1:653593985405:web:881b55d94e85f776304c14',
    messagingSenderId: '653593985405',
    projectId: 'chatmyfriends-ed732',
    authDomain: 'chatmyfriends-ed732.firebaseapp.com',
    storageBucket: 'chatmyfriends-ed732.appspot.com',
    measurementId: 'G-1L26YWQ9F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2f4HmN7gcy3sDecckSJE2Uw1nir4W9A',
    appId: '1:653593985405:android:6d21a93e19ce8677304c14',
    messagingSenderId: '653593985405',
    projectId: 'chatmyfriends-ed732',
    storageBucket: 'chatmyfriends-ed732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwJc-gBOIARFGhjlTWQg4xEQj4VCG34rM',
    appId: '1:653593985405:ios:0bd507b82c9d97c0304c14',
    messagingSenderId: '653593985405',
    projectId: 'chatmyfriends-ed732',
    storageBucket: 'chatmyfriends-ed732.appspot.com',
    iosBundleId: 'com.example.mychats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwJc-gBOIARFGhjlTWQg4xEQj4VCG34rM',
    appId: '1:653593985405:ios:4c58c44dd3fa0e08304c14',
    messagingSenderId: '653593985405',
    projectId: 'chatmyfriends-ed732',
    storageBucket: 'chatmyfriends-ed732.appspot.com',
    iosBundleId: 'com.example.mychats.RunnerTests',
  );
}
